development:
  host: ldap.andrew.cmu.edu
  port: 389
  base: dc=cmu,dc=edu

test:
  host: ldap.andrew.cmu.edu
  port: 389
  base: dc=cmu,dc=edu

production:
  host: ldap.andrew.cmu.edu
  port: 389
  base: dc=cmu,dc=edu
